spring:
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1}
    username: ${APP_DATASOURCE_USERNAME:sa}
    password: ${APP_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  reporting-datasource:
    url: ${REPORTING_DATASOURCE_URL:jdbc:h2:mem:reportingdb;DB_CLOSE_DELAY=-1}
    username: ${REPORTING_DATASOURCE_USERNAME:sa}
    password: ${REPORTING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  dataset-name: ${BATCH_DATASET_NAME:personnes}
  input-file: classpath:/input/personnes.csv
