spring:
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1}
    username: ${APP_DATASOURCE_USERNAME:sa}
    password: ${APP_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: personSyncJob

batch:
  input-file: classpath:/input/personnes.csv
